name: Build Docker Image using Buildx

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: latest