name: build
on: [ workflow_dispatch ]
    

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Init vars
        id: custom-action
        uses: ${{ github.repository_owner }}/custom-action@main

      - name: Print result
        run: |
            echo "Result: ${{ steps.custom-action.outputs.sha-short }}"